
GET http://localhost:3333/transactions HTTP/1.1
Content-Type: application/json
###

GET http://localhost:3333/transactions/edf55e30-47bb-49d8-9093-6b9dabaa48bb HTTP/1.1
Content-Type: application/json
###

GET http://localhost:3333/transactions/summary HTTP/1.1
Content-Type: application/json
###

POST http://localhost:3333/transactions HTTP/1.1
Content-Type: application/json

{
  "title": "Freelancer",
  "amount": 5000.10,
  "type": "credit"
}
###

PUT http://localhost:3333/transactions/edf55e30-47bb-49d8-9093-6b9dabaa48bb HTTP/1.1
Content-Type: application/json

{
  "title": "Freelancer Transaction from Atualizado",
  "amount": 120.20,
  "type": "debit"
}
###

DELETE http://localhost:3333/transactions/21d31d93-e107-455b-b8dd-aedb51ad6ce9 HTTP/1.1
# Content-Type: application/json